### ISSUE TITLE
add vision 

### ISSUE THREAD

**Issue by kassasin** [facebookresearch/metamotivo#5]
Any idea how to add vision or enviroment information to this framework?

**Comment by Miffyli** [comment]
Heya. Do you mean adding vision capabilities to the model itself, or how to add vision observations to the environment? 

For former (adding info to model): currently not supported, this is a research question in-on-itself and will likely need good bit of work to figure out the right recipe.

For latter (adding vision observations): you "only" need to modify the [robot.xml](https://github.com/fairinternal/HumEnv/blob/main/humenv/assets/robot.xml) to add cameras to the right places and then read that observation in the code. I recommend looking at the [DMC code](https://github.com/google-deepmind/dm_control) for how to accomplish that.

**Comment by kassasin** [comment]
thank you very much. I will take a try.

**Comment by Miffyli** [comment]
There is no tutorial for that right now. However you could try changing the robot.xml file I linked to above, and that will change the simulated robot  (i.e., if you replace that with your robot, it will simulate the robot). However I am not 100% sure if the HumEnv code will accomodate it out of the box, and you should double-check that correct info is read and passed along.

**Comment by kassasin** [comment]
understand,I will take a try. Thank you!
